<template>
  <a-layout id="components-layout-demo-fixed-sider">
    <a-layout-sider
      :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 ,background:'#fff'}"
    >
      <div class="sidebar-star">由{{star}}位用户反馈了此问题</div>
      <div class="side-content-item">
        <div class="side-content-left">状态:</div>
        <div class="side-content-right">{{status}}</div>
      </div>
      <div class="side-content-item">
        <div class="side-content-left">所有者:</div>
        <div class="side-content-right">
          {{ owner }}
          <br>...
          <br>...
          <br>...
          <br>...
        </div>
      </div>
      <div class="side-content-item">
        <div class="side-content-left">抄送:</div>
        <div class="side-content-right">
          {{ Cc }}
          <br>...
          <br>...
          <br>...
          <br>...
        </div>
      </div>
      <div class="side-content-item">
        <div class="side-content-left">产品:</div>
        <div class="side-content-right">{{ production }}</div>
      </div>
      <div class="side-content-item">
        <div class="side-content-left">类型:</div>
        <div class="side-content-right">{{ type}}</div>
      </div>
    </a-layout-sider>
    <a-layout :style="{ marginLeft: '200px' }">
      <a-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial' }">
        <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">
          ...
          <br>Really
          <br>...
          <br>...
          <br>...
          <br>long
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>content
        </div>
      </a-layout-content>
      <a-layout-footer :style="{ textAlign: 'center' }">Canaan ©2018 Created by R&D Product</a-layout-footer>
    </a-layout>
  </a-layout>
</template>

<script>
export default {
  name: "detail",
  data() {
    return {
      star: 1,
      status: "untrigger",
      owner: "我我我我我我",
      Cc: "刚哥@10086",
      connect: "",
      production: "IDE",
      type: " 搞快点",
      nextAction: "",
      emergencyLevel: "",
      Title: "",
      id: "",
      content: ""
    };
  }
};
</script>

<style lang="less" scoped>
.sidebar-star {
  text-align: center;
}
.side-content-item {
  padding: 0.5rem;
  .side-content-left {
    text-align: left;
    display: inline-block;
    width: 40%;
    vertical-align: top;
  }
  .side-content-right {
    text-align: left;
    display: inline-block;
  }
}
</style>